### PR TITLE
PR: `remove_item_from_list/2`

### PR DESCRIPTION
**Pull request by nelsonic**
Working on this for: https://github.com/dwyl/mvp/issues/422 which will in turn be used in: https://github.com/dwyl/mvp/issues/420
+ [x] #55 `remove_item_from_list/2`
+ [x] #56 alphabatize map keys in `stringify_map/1` for consistency

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @LuchoTurtle, 👋 
a quick PR to add a basic function (that should be in the standard library ... but isn't 🙄)  #55 
Used in: https://github.com/dwyl/mvp/issues/422
Thanks.

**Comment by nelsonic** [comment]
Reversed the order of the arguments `item, list` becomes `list, item` so that it's pipeable. ref: https://github.com/dwyl/useful/issues/55#issuecomment-1718873747
No further changes required. Please merge. Thanks.

**Review by LuchoTurtle — APPROVED** [review]
Looks great! Thanks! 🥳

**Comment by LuchoTurtle** [comment]
@nelsonic are you going to publishing this or do you want me to?

**Comment by nelsonic** [comment]
Published immediately. Thanks. 👌

**Pull request merged**
