### PR TITLE
PR: `Plug.Upload` Struct Fix issue #52

### PR DESCRIPTION
**Pull request by nelsonic**
This PR:
+ [x] Fixes issue #52 
which is a `BLOCKER`: https://github.com/dwyl/mvp/issues/406 🔥

### CODE REVIEW

**Comment by nelsonic** [comment]
_Patch_ Package published to https://hex.pm/packages/useful/1.12.1 📦 
Testing in: https://github.com/dwyl/gogs/pull/75

**Comment by nelsonic** [comment]
No compilation error:  https://github.com/dwyl/gogs/actions/runs/5864299259/job/15899126010
image

**Comment by nelsonic** [comment]
@LuchoTurtle should be a quick one to review + merge. Please & Thanks. 🙏

**Review by LuchoTurtle — APPROVED** [review]
LGTM!
Thanks!

**Pull request merged**
